name: Deploy Next.js to Server

on:
  push:
    branches: [ deploy/19-cicd ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create .env
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Archive build files
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: .next/
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ubuntu/travloom-frontend
            git pull origin main
            npm install
            echo "${{ secrets.ENV }}" > .env.production
            npm run build
            pm2 restart your-nextjs-app