name: Deploy Next.js to Server

on:
  push:
    branches: [ deploy/19-cicd ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create .env
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: |
            .next/
            public
            package.json
            .env
          include-hidden-files: true
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: nextjs-build

      - name: Deploy build files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "nextjs-build/*"
          target: "/home/ubuntu/travloom-frontend"

      - name: Restart Next.js with pm2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ubuntu/travloom-frontend/nextjs-build
            pm2 restart travloom